flowchart LR
%% generated in 0.00s
    subgraph ifuri_ecobar
        ifuri_ecobar__isActive["isActive"]
        ifuri_ecobar__esc["esc"]
        ifuri_ecobar__navHTML["navHTML"]
    end
    ifuri_ecobar__navHTML --> ifuri_ecobar__esc
    ifuri_ecobar__navHTML --> ifuri_ecobar__isActive
